[package]
name = "qpf"
version = "0.1"
lean_version = "leanprover-community/lean:nightly-2019-08-30"
path = "src"

[dependencies]
mathlib = {git = "https://github.com/leanprover-community/mathlib", rev = "313fe11b10c8c7f000307d28cd85dc27dfef581c"}
